### ISSUE TITLE
Freckles broken with non-ascii task name

### ISSUE THREAD

**Issue by lalmeras** [makkus/freckles#28]
* freckles version: 0.4.3 (git version activated)
* Python version: 2.7.13
* Operating System: Fedora 26

### Description

I write a frecklecute repository with a single task role called unicode that uses debug module (https://github.com/powo-roles/test.freckles/blob/master/unicode/tasks/main.yml).

The frecklecute script fails with a parsing error due to unknown charset setting.

### What I Did

```
frecklecute -r https://github.com/powo-roles/test.freckles.git test-unicode
Traceback (most recent call last):
  File "/home/lalmeras/.local/bin/frecklecute", line 11, in <module>
    sys.exit(cli())
  File "/home/lalmeras/.local/inaugurate/conda/envs/inaugurate/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/lalmeras/.local/inaugurate/conda/envs/inaugurate/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/lalmeras/.local/inaugurate/conda/envs/inaugurate/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lalmeras/.local/inaugurate/conda/envs/inaugurate/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lalmeras/.local/inaugurate/conda/envs/inaugurate/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/lalmeras/.local/inaugurate/conda/envs/inaugurate/lib/python2.7/site-packages/freckles/commands.py", line 185, in command_callback
    ask_become_pass=ask_become_pass, config=self.config, run_box_basics=True)
  File "/home/lalmeras/.local/inaugurate/conda/envs/inaugurate/lib/python2.7/site-packages/freckles/utils.py", line 658, in create_and_run_nsbl_runner
    display_ignore_tasks=ignore_task_strings, pre_run_callback=pre_run_callback)
  File "/home/lalmeras/.local/inaugurate/conda/envs/inaugurate/lib/python2.7/site-packages/nsbl/nsbl.py", line 670, in run
    callback_adapter.add_log_message(line)
  File "/home/lalmeras/.local/inaugurate/conda/envs/inaugurate/lib/python2.7/site-packages/nsbl/output.py", line 189, in add_log_message
    self.output.start_task(self.current_task_name, self.current_role, self.current_task_is_dyn_role)
  File "/home/lalmeras/.local/inaugurate/conda/envs/inaugurate/lib/python2.7/site-packages/nsbl/output.py", line 327, in start_task
    self.print_task_string("   - {} => ".format(task_name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 26: ordinal not in range(128)
```

**Comment by lalmeras** [comment]
Surely linked to a missing or wrong encoding used to read ansible output. This encoding should be set accordingly with ansible setting.

**Comment by lalmeras** [comment]
PR available here: https://github.com/makkus/nsbl/pull/43

Some explanation on the encountered issue here: https://stackoverflow.com/questions/3235386/python-using-format-on-a-unicode-escaped-string

From this stackoverflow source, a more radical fix would be to use:

```
from __future__ import unicode_literals
```
This is maybe a better choice, but it is too difficult to me to appreciate potential regressions.

**Comment by makkus** [comment]
Yeah, apparently there is an issue with `import unicode_literals` and the click library/Python 3: http://click.pocoo.org/5/python3/#unicode-literals

Which was the reason I removed that import everywhere I had it for now. Not sure if this would in any way affect the output processing. So, I think for now your solution is a saver bet. Thanks!
